version: "3.9"  # optional since v1.27.0
services:
  app:
    image: php:7.4-fpm-alpine3.13
    ports:
      - "9000:9000"
    volumes:
      - ./app/rucshop/src:/var/www/html
      - ./app/rucshop/vendor:/var/www/html/vendor
  web:
    image: nginx:1.21.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/conf.d/default.conf
  composer:
    image: composer
    volumes:
      - ./app/rucshop:/app
    command: composer install

